---
version: '3'

services:
  projectsend:
    hostname: 'projectsend'
    container_name: 'projectsend'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
      - 'UMASK=022'
      - 'MAX_UPLOAD=<5000>'
    image: 'ghcr.io/linuxserver/projectsend'
    restart: 'unless-stopped'
    ports:
      - '127.0.0.1:5555:80'
    networks:
      - proxy
    security_opt:
      - 'no-new-privileges:true'
    volumes:
      - '/opt/appdata/projectsend:/config:rw'
      - '/opt/appdata/projectsend:/data:rw'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'dockupdater.enable=true'
      - 'traefik.http.routers.projectsend-rtr.entrypoints=https'
      - 'traefik.http.routers.projectsend-rtr.rule=Host(`projectsend.${DOMAIN}`)'
      - 'traefik.http.routers.projectsend-rtr.tls=true'
      - 'traefik.http.routers.projectsend-rtr.tls.certresolver=dns-cloudflare'
      - 'traefik.http.routers.projectsend-rtr.middlewares=chain-authelia@file'
      - 'traefik.http.routers.projectsend-rtr.service=projectsend-svc'
      - 'traefik.http.services.projectsend-svc.loadbalancer.server.port=80'

networks:
  proxy:
    driver: bridge
    external: true
