---
version: '3'

services:
  code-server:
    hostname: 'code-server'
    container_name: 'code-server'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
      - 'UMASK=022'
      - 'PASSWORD=password'
      - 'HASHED_PASSWORD=#fillthisself'
      - 'SUDO_PASSWORD=sudopassword'
      - 'SUDO_PASSWORD_HASH=#fillthisself' 
    image: 'ghcr.io/linuxserver/code-server'
    restart: 'unless-stopped'
    ports:
      - '127.0.0.1:8443:8443'
    networks:
      - proxy
    security_opt:
      - 'no-new-privileges:true'
    volumes:
      - '/opt/appdata/code-server:/config:rw'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'dockupdater.enable=true'
      - 'traefik.http.routers.code-server-rtr.entrypoints=https'
      - 'traefik.http.routers.code-server-rtr.rule=Host(`code-server.${DOMAIN}`)'
      - 'traefik.http.routers.code-server-rtr.tls=true'
      - 'traefik.http.routers.code-server-rtr.tls.certresolver=dns-cloudflare'
      - 'traefik.http.routers.code-server-rtr.middlewares=chain-authelia@file'
      - 'traefik.http.routers.code-server-rtr.service=code-server-svc'
      - 'traefik.http.services.code-server-svc.loadbalancer.server.port=8443'

networks:
  proxy:
    driver: bridge
    external: true
