---
version: '3'

services:
  mount:
    cap_add:
      - 'SYS_ADMIN'
    container_name: 'mount'
    devices:
      - '/dev/fuse:/dev/fuse'
    ports:
      - '7755:8080'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
    image: 'ghcr.io/doob187/mountv2'
    networks:
      - proxy
    restart: 'unless-stopped'
    labels:
      - 'dockupdater.enable=false'
    security_opt:
      - 'apparmor=unconfined'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/opt/appdata/mount:/config:rw'
      - '/mnt:/mnt:shared'
      - '/var/run/docker.sock:/var/run/docker.sock'

networks:
  proxy:
    driver: bridge
    external: true
