---
version: '3'

services:
  uploader:
    cap_add:
      - 'SYS_ADMIN'
    container_name: 'uploader'
    devices:
      - '/dev/fuse:/dev/fuse'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
    image: 'ghcr.io/doob187/uploaderv2'
    restart: 'unless-stopped'
    ports:
      - '127.0.0.1:7777:8080'
    networks:
      - proxy
    security_opt:
      - 'apparmor:unconfined'
    networks:
      - proxy
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/opt/appdata/uploader:/config:rw'
      - 'unionfs:/mnt'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'dockupdater.enable=true'
      - 'traefik.http.routers.uploader-rtr.entrypoints=https'
      - 'traefik.http.routers.uploader-rtr.rule=Host(`uploader.${DOMAIN}`)'
      - 'traefik.http.routers.uploader-rtr.tls=true'
      - 'traefik.http.routers.uploader-rtr.tls.certresolver=dns-cloudflare'
      - 'traefik.http.routers.uploader-rtr.middlewares=chain-authelia@file'
      - 'traefik.http.routers.uploader-rtr.service=uploader-svc'
      - 'traefik.http.services.uploader-svc.loadbalancer.server.port=8080'

networks:
  proxy:
    driver: bridge
    external: true

volumes:
  unionfs:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt
